name: 'Install Node dependencies'
description: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Bun 🐰
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Cache node modules ✨
      uses: actions/cache@v3
      id: cache-modules
      env:
        cache-name: cache-node-${{ matrix.node }}-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
        restore-keys: ${{ runner.os }}-cache-${{ env.cache-name }}-

    - name: Install Dependencies 🔧
      if: steps.cache-modules.outputs.cache-hit != 'true'
      shell: bash
      run: bun install