name: "Pull Request"
concurrency: ${{ github.workflow }}
on:
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - uses: ./.github/actions/node-dependencies
      - name: Run test
        run: yarn test:ci